from PyQt5 import QtCore, QtGui, QtWidgets

from utils.relative_path import resource_path


class ExplorerUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(685, 405)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(667, 0))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.dirView = QtWidgets.QTreeView(self.splitter)
        self.dirView.setFrameShape(QtWidgets.QFrame.Box)
        self.dirView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dirView.setSortingEnabled(True)
        self.dirView.setAnimated(True)
        self.dirView.setObjectName("dirView")
        self.dirView.header().setVisible(False)
        self.dirView.header().setMinimumSectionSize(20)
        self.fileView = QtWidgets.QTreeView(self.splitter)
        self.fileView.setFrameShape(QtWidgets.QFrame.Box)
        self.fileView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.fileView.setLineWidth(1)
        self.fileView.setMidLineWidth(0)
        self.fileView.setObjectName("fileView")
        self.fileView.header().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setMovable(False)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        MainWindow.insertToolBarBreak(self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.moveBackAction = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("move_back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveBackAction.setIcon(icon)
        self.moveBackAction.setObjectName("moveBackAction")
        self.moveForwardAction = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(resource_path("move_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveForwardAction.setIcon(icon1)
        self.moveForwardAction.setObjectName("moveForwardAction")
        self.moveMyComputeAction = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(resource_path("move_to_my_computer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveMyComputeAction.setIcon(icon2)
        self.moveMyComputeAction.setObjectName("moveMyComputeAction")
        self.moveUpAction = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(resource_path("move_up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveUpAction.setIcon(icon3)
        self.moveUpAction.setObjectName("moveUpAction")
        self.createNewDirAction = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(resource_path("create_new_dir.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createNewDirAction.setIcon(icon4)
        self.createNewDirAction.setObjectName("createNewDirAction")
        self.createNewFileAction = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(resource_path("create_new_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createNewFileAction.setIcon(icon5)
        self.createNewFileAction.setObjectName("createNewFileAction")
        self.pathEditAction = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(resource_path("edit_path.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pathEditAction.setIcon(icon6)
        self.pathEditAction.setObjectName("pathEditAction")
        self.cutAction = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(resource_path("cut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cutAction.setIcon(icon7)
        self.cutAction.setObjectName("cutAction")
        self.copyAction = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(resource_path("copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyAction.setIcon(icon8)
        self.copyAction.setObjectName("copyAction")
        self.pasteAction = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(resource_path("paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pasteAction.setIcon(icon9)
        self.pasteAction.setObjectName("pasteAction")
        self.renameAction = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(resource_path("rename.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.renameAction.setIcon(icon10)
        self.renameAction.setObjectName("renameAction")
        self.deleteAction = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(resource_path("delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteAction.setIcon(icon11)
        self.deleteAction.setObjectName("deleteAction")
        self.settingsAction = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(resource_path("settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsAction.setIcon(icon12)
        self.settingsAction.setObjectName("settingsAction")
        self.findAction = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(resource_path("find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findAction.setIcon(icon13)
        self.findAction.setObjectName("findAction")
        self.openAction = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(resource_path("open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAction.setIcon(icon14)
        self.openAction.setObjectName("openAction")
        self.accountSettingsAction = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(resource_path("user.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountSettingsAction.setIcon(icon15)
        self.accountSettingsAction.setObjectName("accountSettingsAction")
        self.logInAction = QtWidgets.QAction(MainWindow)
        self.logInAction.setIcon(icon15)
        self.logInAction.setObjectName("logInAction")
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.moveBackAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.moveForwardAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.moveUpAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.moveMyComputeAction)
        self.toolBar.addSeparator()
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.openAction)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.createNewDirAction)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.createNewFileAction)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.pathEditAction)
        self.toolBar_2.addSeparator()
        self.toolBar_3.addSeparator()
        self.toolBar_3.addAction(self.cutAction)
        self.toolBar_3.addSeparator()
        self.toolBar_3.addAction(self.copyAction)
        self.toolBar_3.addSeparator()
        self.toolBar_3.addAction(self.pasteAction)
        self.toolBar_3.addSeparator()
        self.toolBar_3.addAction(self.renameAction)
        self.toolBar_3.addSeparator()
        self.toolBar_3.addAction(self.deleteAction)
        self.toolBar_3.addSeparator()
        self.menu.addAction(self.createNewDirAction)
        self.menu.addAction(self.createNewFileAction)
        self.menu.addAction(self.findAction)
        self.menu_2.addAction(self.cutAction)
        self.menu_2.addAction(self.copyAction)
        self.menu_2.addAction(self.pasteAction)
        self.menu_2.addAction(self.renameAction)
        self.menu_2.addAction(self.deleteAction)
        self.menu_3.addAction(self.logInAction)
        self.menu_3.addAction(self.settingsAction)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Проводник"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Изменить"))
        self.menu_3.setTitle(_translate("MainWindow", "Настройки"))
        self.moveBackAction.setText(_translate("MainWindow", "Перейти назад"))
        self.moveForwardAction.setText(_translate("MainWindow", "Перейти вперед"))
        self.moveMyComputeAction.setText(_translate("MainWindow", "Перейти в \"Мой компьютер\""))
        self.moveUpAction.setText(_translate("MainWindow", "Перейти в верхнюю папку"))
        self.createNewDirAction.setText(_translate("MainWindow", "Создать новую папку"))
        self.createNewFileAction.setText(_translate("MainWindow", "Создать новый файл"))
        self.pathEditAction.setText(_translate("MainWindow", "Поменять путь"))
        self.cutAction.setText(_translate("MainWindow", "Вырезать"))
        self.copyAction.setText(_translate("MainWindow", "Копировать"))
        self.pasteAction.setText(_translate("MainWindow", "Вставить"))
        self.renameAction.setText(_translate("MainWindow", "Переименовать"))
        self.deleteAction.setText(_translate("MainWindow", "Удалить"))
        self.settingsAction.setText(_translate("MainWindow", "Настройки приложения"))
        self.findAction.setText(_translate("MainWindow", "Поиск"))
        self.openAction.setText(_translate("MainWindow", "Открыть"))
        self.accountSettingsAction.setText(_translate("MainWindow", "Настройки аккаунта"))
        self.logInAction.setText(_translate("MainWindow", "Войти"))