from PyQt5 import QtWidgets, QtCore, QtGui


class FindUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 483)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.findButton = QtWidgets.QPushButton(self.centralwidget)
        self.findButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.findButton.setObjectName("findButton")
        self.verticalLayout.addWidget(self.findButton)
        self.findName = QtWidgets.QLineEdit(self.centralwidget)
        self.findName.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.findName.setText("")
        self.findName.setObjectName("findName")
        self.verticalLayout.addWidget(self.findName)
        self.findPath = QtWidgets.QLineEdit(self.centralwidget)
        self.findPath.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.findPath.setText("")
        self.findPath.setObjectName("findPath")
        self.verticalLayout.addWidget(self.findPath)
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.openButton.setObjectName("openButton")
        self.verticalLayout.addWidget(self.openButton)
        self.filesWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.filesWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.filesWidget.setObjectName("filesWidget")
        self.filesWidget.setColumnCount(0)
        self.filesWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.filesWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Введите название файла"))
        self.findButton.setText(_translate("MainWindow", "Поиск"))
        self.findName.setPlaceholderText(_translate("MainWindow", "Название файла"))
        self.findPath.setPlaceholderText(_translate("MainWindow", "Путь к директории, в которой ищем"))
        self.openButton.setText(_translate("MainWindow", "Перейти"))
