from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize


class LoginUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(QSize(213, 245))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(10, 120, 191, 20))
        self.password.setText("")
        self.password.setMaxLength(32)
        self.password.setObjectName("password")
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(10, 60, 191, 20))
        self.login.setMaxLength(32)
        self.login.setObjectName("login")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(30, 180, 51, 23))
        self.loginButton.setObjectName("loginButton")
        self.registrationButton = QtWidgets.QPushButton(self.centralwidget)
        self.registrationButton.setGeometry(QtCore.QRect(90, 180, 91, 23))
        self.registrationButton.setObjectName("registrationButton")
        self.save_data = QtWidgets.QCheckBox(self.centralwidget)
        self.save_data.setGeometry(QtCore.QRect(10, 150, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_data.setFont(font)
        self.save_data.setObjectName("save_data")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход"))
        self.label.setText(_translate("MainWindow", "Введите логин"))
        self.label_2.setText(_translate("MainWindow", "Введите пароль"))
        self.loginButton.setText(_translate("MainWindow", "Войти"))
        self.registrationButton.setText(_translate("MainWindow", "Регистрация"))
        self.save_data.setText(_translate("MainWindow", "Сохранить данные при входе"))
